### ISSUE TITLE
Refactor needed post-removal of Gemini

### ISSUE THREAD

**Issue by noahwsmith** [mjordan/islandora_premis#2]
> Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "islandora.gemini.lookup". in Drupal\Component\DependencyInjection\Container->get() (line 153 of /var/www/drupal/web/core/lib/Drupal/Component/DependencyInjection/Container.php).

We're running https://github.com/Islandora/islandora/tree/8.x-1.x after acceptance of https://github.com/Islandora/islandora/pull/822 so my suspicion is that islandora_premis needs to have references to Gemini removed. I saw @dannylamb and @ruebot discussing a similar issue yesterday in the #islandora8 slack channel.

**Comment by mjordan** [comment]
I will fix. Thanks for reporting.

**Comment by noahwsmith** [comment]
Notes on testing: I updated our module and now are getting a RDF/Graph error:

```
Error: Class 'EasyRdf\Graph' not found in islandora_premis_islandora_premis_turtle_alter() (line 32 of /var/www/drupal/assets/sites/all/modules/custom/islandora_premis/islandora_premis.module)
#0 [internal function]: islandora_premis_islandora_premis_turtle_alter('53', NULL)
#1 /var/www/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(403): call_user_func_array('islandora_premi...', Array)
#2 /var/www/drupal/assets/sites/all/modules/custom/islandora_premis/src/Controller/IslandoraPremisPremisController.php(26): Drupal\Core\Extension\ModuleHandler->invokeAll('islandora_premi...', Array)
#3 [internal function]: Drupal\islandora_premis\Controller\IslandoraPremisPremisController->main()
#4 /var/www/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#5 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#6 /var/www/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#7 /var/www/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#8 /var/www/drupal/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#9 /var/www/drupal/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /var/www/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
```

**Comment by mjordan** [comment]
Can you clear your cache to see if that helps?

**Comment by noahwsmith** [comment]
Just checked that and no joy. I wonder if we need to do something like this:

https://github.com/asulibraries/chullo/blob/e07b54dbad0d652c4f9997eb707073cd20a7c388/src/IFedoraApi.php#L22


here:
https://github.com/mjordan/islandora_premis/blob/8.x-1.x/islandora_premis.module#L3

--

Noah Smith

Founder + CEO

Pronouns: he/him/his. Scheduling a meeting with me? View my availability
***@***.***&ctz=America/New_York&mode=WEEK>
Born-Digital | 84 Russell St, Hadley MA | (413) 259-6777 | born-digital.com

**Comment by mjordan** [comment]
Yes, that would be a good idea. Can you open a PR or do you want me to take care of it? I'm not getting that error so my environment is presumably different from yours.

**Comment by mjordan** [comment]
I've added the class aliases to the "add_easyrdf_alias" branch. Can you test?

**Comment by noahwsmith** [comment]
Works GREAT- thank you!

**Comment by mjordan** [comment]
Thanks for testing.
